language: node_js
node_js: 
    - 6
    - 5
branches:
  except:
  - dev-wia
before_script:
- curl https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz -O
- tar -Jxvf ffmpeg-release-64bit-static.tar.xz
- export PATH=$PATH:$PWD/ffmpeg-3.2.4-64bit-static 
- curl https://github.com/mediagoom/mg/releases/download/v0.1.3/mg -O -L
- chmod +x mg
- mv mg $PWD/ffmpeg-3.2.4-64bit-static
script:
- npm install
- npm run build
- npm start
- npm test
after_script:
- npm stop

