language: node_js
node_js:
- 10
- 11
- 8
env:
  global:
  - DEBUG: opflow:processor
  - secure: ZF6lLmIb5657ZVGyl3CER9xgQmSmBisqVhq4IIWw7VbAax3QJSHFInV4INm/OVppEN3djsn5aiMltE0QJlWgqvUg+/TJQG4Lg6jaYxx9OYnaOJYhhqu1T6/Zek6dJQPRyCpYCGBSv5neQrRwEp1X80uscxcFmn2GeM7nsu6ODM9uWRNhAX4bEGbBNGFfkANtspWAsKOXWEQHMCEk2Q5utHdPlhxNBIqJFapkyAjCVqhhpnYMh8HZYh9cR9q3t6v/oubQcyYohUjYcf9WSLIl4CkTaA7XCfLF1ZsFJ8IpfRLewbMFN/mXzItwnJuxq2TRuLb9ijnXKAeIZEMg/Ffmbc4I1d8JUqDbBw3BUdpJHfrzMECGr9cv21NxQkeBips/FPna3q1edcLiRGFBE4qy5AEknyqfs4QeWnKNJWrj799Qz96ebnsPCRwoupnMoBBILsEqA2FFLLb0/0wmcXmWzTWdK+fYWnuoZ5LIqz+y63JYk6bEx4cGOrDE/Z2upTHWjd2q5hqQ9N8lFOl8fXzfCnm2as1LsUifJwznblirMq3pgg8HWYpgX5NqxdhGH7Df4YNMnPcp1nBNqzSxULH76741w5K24Mx8kwvTJC2mMo9RABovHrkJ/ezChorw48oBxk5aPwCAQM4jE1BmV1Z2qHE2QxLd+YJekOu3IBmAods=
  - secure: Ecmk5mF9H1+LV01B7PadEZHgCwdI0nyWlsOVrhTxrOCFH/7mASg7IRP09qM3xb7ufTG2XwdBOll3FVFXhPjtNfcuPD8ugkSlMCpjeyjK47lGhl2QxRe+NKIL5tD7PvYV+91zRdczggjWFxB4dQler5u/9b/jscJoXjWhRC9ZNYr2IhwKpKwJidToJg0zO2YUaSd+jmhKjv2mOOedGdefTVItlXgDFyqhmIUgqM9TphmNeNAtjWvfyimNRBFmLmjrgbwKlR9bEbhtUzJLXLEwRyjpmlt5WaYBD1HV0asrZqN83FbtmReB3x7AHa9aPwc0yBav7brnRsT8z/np2VFwZJ/FuFwGgM2VYSSMnaMKZoPElEUM0srNmGYxN8svvhG1LVcV9gmKA5P2vefA1XXVBU+H57nCgh/qSHugEF0V4Ihd2rYPqRmQ9kpUeeheVw8QybnqlNpxt84e9dYSWjaMvvQZOXfH0gQNmLW8+/+7m43K0HBhd4yFzlc5N4kTO4s4B4xqf4vX9EbIZ8iy2a+87RtubcfyZMjpYEa6K8L5K0Cn0xEr6dSQyZeE0q2xwvL12fH774hz6kqip5DrxDzHapJ2ZIdBH6I3C7ogQ+0ZeFp7knW1nG3Y64XmM7nCREdXGHy3c1mQNicxHWv/9NwINNNUSo85LSJ7YMsTNJdzQh8=
  - secure: j9TG6nIgznNsvrc860lOyFA7q6VrDgOoPVWEJFNIyfChJzU/VS6Dftxb53b13YJ2LSD3oSg4yQr1/+odcf4/dSHYSpk7hRrmrmZ+y3FNj7rw8a59uhiwAbFDdhMHtGfkU3JZ1RiHNRkyRpVNRzYEqCg+o5l7+8ay5UZfT064pSBfdjTuQH2fxpWIp7Ccs4oMoXL3YYcPAj41uMnuxwiJa3X4HD3m3EQknW8ZG3KzUEl70v+sdg0eKq6rYCUEC2/P5xeUUmCERdbc6nl5utVLRh3Jv1dp5bFAMQjDdtgP35iHzL1bOkrkOcUNciWMF41SdDZ6a7i2gbO6OHiLbEAyO6/tDvDdp+lCxlK21H897QNnaCB6qFOxQXsrvoY/rlHZmeGhPlFLRTqOgQPxeNrLqzqJfvep3R20ofCXg+b/dDKeCLakEAlb2kGjAKbkJuvFnou5olLytTlCUsRRdoiOevfZaKOK4SVYJU6KU5zRbWBHvOuu7MFG+h48t5fRTC4w9HRfNbRSg/3L9mMXY9cGtETWM7QGaqDH0aje7FH4cdNV/T0V7VJBc1sMAF16HyRMtZq5uuWnve3HQBo1lcdelxd9D8w9a31SxsbFnRz2XI61e9AO+Stln0g3BPMUGE6Hr0BaJd63RTGxdXh1ub5yKYmBjHFb+pIwa6OY3HWwAI0=
  matrix:
  - NODE_ENV: development
  - NODE_ENV: production
branches:
  except:
  - dev-wia
services:
- docker
before_install:
- python ./version.py
- npm i -g npm@5.6.0
- echo "$DOCKERHUBPSW" | docker login --username "$DOCKERHUBUSR" --password-stdin
install:
- npm install
- npm install --only=dev
- npm install coveralls codecov nyc
script:
- npm run cov-all
- ls ./.nyc_output
- "./node_modules/.bin/nyc report --reporter=text-lcov | coveralls"
- "./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && codecov"
- docker build -t "mediagoom/node-play:$TRAVIS_BRANCH" .
after_script:
- docker push "mediagoom/node-play:$TRAVIS_BRANCH"
deploy:
- provider: npm
  email: info@mediagoom.com
  skip_cleanup: true
  api_key:
    secure: GySL9YnyAUPDhUy/JQ+/e9+GZ2I8PPdyazzqJjKyrn/BDPu5v5NcEH+TlrLfiTvQ6gZAu4dJ8a+KIa92QgJNQSxEvNHU1euuUFpVX6IQAsxMIVUh2aZsHYOMmQcjCb4rzsAXVpHjjE3gTUkpxa8xKkLuWtZcx06AG7XOD++wcpFx3jar9ACzw3AJ7JuPvFnm1a+JI9tv42l+49JYzlzSIKC3/YW6s0NvLExEpGYkIm04OV7Qhp1hTg4myBre2F4WFC3s8n7NCtDomDgPSK1T4jjU64kouhyCW80wVcD00k1Op7SlmBpn/icHzMfUHW6WeTcR9iXe6QWo27JNntayLlNOB5mz2tdspULWlynDFhTZseGhQY6s8/Y5mkp3RPXKNwfplosP2ZpTBhyqbK5fNW9chWGe/kgxs4fGyiE1i0nxy3UNOVI+xabOrrqs9cGIQfWgc+WI3avOoJwJGiatTd/QGiGkEjFTwrg+kcU620NDberDClr2Hahr0DSYU+qOXELocJUIv68oJUuKW+UjaBCmpnP/fbYXx+jOuzuOuJYbk5F8BUVrFJM6T851rHaiNSNWTEQmeR1+2Na+P5dMAmanOG4dcHfqJmflhJGPhk271iMcL4loE0q87LqOYNb1C2gQiogTbY6F547gZrV8IHWNIML3B1NmxmpfaKXMDRM=
  on:
    tags: true
    repo: mediagoom/node-play
    node: 8
- provider: script
  script: bash -c "docker build -t 'mediagoom/node-play:latest' . && docker push 'mediagoom/node-play:latest'"
  on:
    tags: true
    repo: mediagoom/node-play
    node: 10
