language: node_js
node_js:
- 6
- 5
- 4
branches:
  except:
  - dev-wia
before_script:

script:
- npm run build
- npm start
- cat ./out.log
- npm test
after_script:
- npm stop
deploy:
  api_key:
    secure: gUVFT7Uw3GSAm+vrrypj1H7nbS5ceJN7gTY20K1z3jvNvQOD9rThOTqWX1RUjorYyJ38oq1bgmhh+prl2yS+atrgQqdZfoLhz9hjUM1ZsNN6kHw/Zftv8cNNxOqWm+qQvQvdYoQ6poQBjK0XJI1jeic0MSDrESKpgLZB2uwUI7ZuSIUgdIcplOL1GJQgIo0WYrLu0aVYEPXV8KfltfAHiyKUXstNHQuJrDMiAwbkfGkxzc6Uv14z3qGuf9sbEwp8SzlELygAYVnuSDisvRf+6+NlbSiW97EoX4RGhA9hWpXHOplyGPsmBXTvBGwnKIpTXWt4NGv2Wri9q/oufYcoCA3s9GRBK5NsXJ9Vrc/cKbOzJ8rLHKOIIF0Zk+QnZStc8yyG3VDkA+cYkLbVwnV82inLLrwktXaSCsxsCYscICxNGoCEXkPn9SOwyVCSHAGuZ40rFyfaWiyi4dCsKxPTTz8uZjA2aHJtu7d6BNyp5vA06aoGF+z3SuqDl5uQWo/4zVdtEYzA7uhUTeB+/+V5YmYwxGUh170HglI1xfapAxwuo9uBA9vEvFmsIt4R0T6Frgc+bNrmK2YYtx2lQLJK51d4qZ2NpT5W9sUpUPMU5H/VTXs99idac7FnjkKCmyLEuQ7UXRENb+s9vrogHXUNiQBrsNFoEXzAtLb47gE1j9M=
