language: node_js
node_js: 
    - 6
    - 5
branches:
  except:
  - dev-wia
before_script:
- curl https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz -O
- tar -Jxvf ffmpeg-release-64bit-static.tar.xz
- mv ffmpeg-3.2.4-64bit-static/ffmpeg /usr/bin
- curl https://github.com/mediagoom/mg/releases/download/v0.1.3/mg -O
- chmod +x mg
- mv mg /usr/bin
script:
- npm install
- npm run build
- npm start
- npm test
after_script:
- npm stop

