language: node_js
node_js:
- 10
- 9
- 8
env:
  DEBUG: xnode-play:statmanfs,xopflow:processor
  secure: E0j8TxDtzsMW6zVLE6ix2NOOBZddl6izoKfcXL0U7PgDwTXjNlsHwJxeyBVtWgb6NMLmEfOkDwuUO+6t0Myy0CY4kxH3Q+V3pQLYq+bkwfP4NNi6Kbubb9258H/IKTdQbC2d/JrAUz2ez/oPBAG65xu6LYw9gMyl2g3tED1I2q+XkYgn15WVmOthsonDphCtIKa61DtySDU4V5r9EiuctWPtHOwx1TgnCjuAfsZk2cq7t/BdfH/PAip1tiHirosqxWhwf6DFyw005LlYioOtCMqP6xlInWbNPchJlgaZgprkuFd+n2/b1cwukA1OYsqVrpSugUnGS3KPlSC475usHljwNrW4fWM/GKrAonpbOs0L7ZeFoHSrp4LRr9RAFWvmFBTg7YUtjqvN5EfDz9qar75ERBoCMnW6GfioZ2JBGZi4Yd770i1FXa2/+uUQh9BVE/BfgE56b3di1LpukM4B4xhGu5vuq1ID1Lt7eawYN/GYDgGWpL4zHLpTkjsQvaKmoZcO00Pgbmi/ZvQv/QCv/wsyIl3Q+Bf1Wwdy+KnZtoL7tMV/73zUIjwS62BDlalr1B2oN204GyKQhOvwHpjFtbB+pXdgnFB1IWTnqjKrvNNC86Am0YWLEFbNhP+knzyjTUVnHOuQfv+grreRHKHQp5PFk6ye21u93SMEfVJX97Y=
branches:
  except:
  - dev-wia
before_install:
- python ./version.py
- npm install
- npm install coveralls codecov
script:
- "./node_modules/.bin/nyc npm run test"
- mv ./.nyc_output ./.nyc_tmp
- "./node_modules/.bin/nyc npm run integration"
- mv ./.nyc_tmp/* ./.nyc_output
- ls ./.nyc_output
- "./node_modules/.bin/nyc report --reporter=text-lcov | coveralls"
- "./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && codecov"
after_script:
- npm stop
deploy:
- provider: npm
  email: info@mediagoom.com
  skip_cleanup: true
  api_key:
    secure: l+bBmf0gBoDoXIk756Mic4vfBP5wvmHOM8FK5Yz3GQYVspM/IVVOrNCwHmcEwWUBEzCqXHq/qAcQ8SI5O7CtBSFNlIFbfKxzuWB8W2ovNWYcOCkFQ7nhCb52HvBBG2+r/GJaWtFp/vBy/Tu/FnPTXtHhprfUUdafX50FzSshfOC+KtNuI2RIhIu8yh9EXq4jdrlwdx/9NvvYTA0vSd1A4mXmeiwtJe92c9qsxiqEbtLZf+F75otf8/B7EZv4A+XZcZua/8M+tZdEApHpvxIC1jwjVQv4tvB32+mmYhOkVWsWWQKfSvXN3vxU0co5kXHm+AnOL0+XNnEVOJH54VRHd9ktyzHqfa68mqp7vzn3Qnr6vssmwRGecn6wGqZfY+Urmq0aV2d6DywPoQquzmI39MFGD4UDzHJzvKZ6G/N194jKg8Q9ofUerNlrCHFXh533T0v3JWrELJSI+D+/M7bRqrfZicnGlEziQrlOA70SpIKdrJnkchjED3xxX4nxOWZnEsX+qDnvNAJTZgXNwUdc3HAmbZkWEdQIfKQvYUMn6r7kkF3QpxvjCw32lqh5VNBTLt3DPijN47C5RaGnbeLh9su7hhouCH8UoSMUI6IKUN17Sq6GCNd1X1DAwcumHET9SzV6It+6/fcFIDEecTOkCE1if84d+7pKdqGbDGz5guQ=
  on:
    tags: true
    repo: mediagoom/node-play
    node: 8
