language: node_js
node_js:
- 10
- 9
- 8
env:
  global:
  - DEBUG: opflow:processor
    COVERALLS_REPO_TOKEN:
      secure: hQFwRYJYpC7h7YNGlnHH73+dFxDbTM0gvtu5ef5gYfw5NlcE3QFUbnmyU4JYKaQL6W2UxpxP+5GVI2FnJH/bha1K2TskPGdxBc5W75hyT6wBafrkqCcVF3HkXPiQJCwLd2/87LqC31H2olsWLDV40avFRjqXD8tEIorI+asdXoYxR6plw9BZnLzitRpv3GUxjqEyGYz6dhB2qGtdp8xXLVcnwnXEGdQKXQrqJQ5jN8dhfG4jfgr0rZ7xMEPZCSEpZOvR/1eKZK/OSa9Ny5+6IRV6Arhqy1Ztf6AV2Y8+IUNcGsPDOrgA3cZre7i6EfofokrHH3EVNUfP4NblDzGSvAfU1E6CefkTBeVZiMYp2xs7MceID304V/UlI6xnekHC8CW8WGbnWfmM+eD6SV8CVtv3Ap279clinMbqZGpyqmu2ocMavlx6e/l44BbEwe7Tpo3eSLWLHqGVpycfp+eRQVsXVRCwcnkgFSGmd+OGkvyYYuZ9YXAGPoiE+tL9k22KBHBGzOGSSXHPLhefItczNs8OJRfoTKyF9Clf8Pxzp89DX6nCvLFSm7rK4gsTAb9Zgv20B6lNnfbSTSHmTzjJkJZq0QB1r9mKr8x9iWWwYWgzewaAubC1vV+ThcUzLFhSQlAyW+ZixVisbW8sXfXZ/kHTLzK5m7pJRv3APYLPO40=
  matrix:
  - NODE_ENV: development
  - NODE_ENV: production
branches:
  except:
  - dev-wia
before_install:
- python ./version.py
- npm i -g npm@5.6.0
install:
- npm install
- npm install --only=dev
- npm install coveralls codecov nyc
script:
- npm run cov-all
- ls ./.nyc_output
- "./node_modules/.bin/nyc report --reporter=text-lcov | coveralls"
- "./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && codecov"
after_script: 
deploy:
  - provider: npm
    email: info@mediagoom.com
    skip_cleanup: true
    api_key:
      secure: GySL9YnyAUPDhUy/JQ+/e9+GZ2I8PPdyazzqJjKyrn/BDPu5v5NcEH+TlrLfiTvQ6gZAu4dJ8a+KIa92QgJNQSxEvNHU1euuUFpVX6IQAsxMIVUh2aZsHYOMmQcjCb4rzsAXVpHjjE3gTUkpxa8xKkLuWtZcx06AG7XOD++wcpFx3jar9ACzw3AJ7JuPvFnm1a+JI9tv42l+49JYzlzSIKC3/YW6s0NvLExEpGYkIm04OV7Qhp1hTg4myBre2F4WFC3s8n7NCtDomDgPSK1T4jjU64kouhyCW80wVcD00k1Op7SlmBpn/icHzMfUHW6WeTcR9iXe6QWo27JNntayLlNOB5mz2tdspULWlynDFhTZseGhQY6s8/Y5mkp3RPXKNwfplosP2ZpTBhyqbK5fNW9chWGe/kgxs4fGyiE1i0nxy3UNOVI+xabOrrqs9cGIQfWgc+WI3avOoJwJGiatTd/QGiGkEjFTwrg+kcU620NDberDClr2Hahr0DSYU+qOXELocJUIv68oJUuKW+UjaBCmpnP/fbYXx+jOuzuOuJYbk5F8BUVrFJM6T851rHaiNSNWTEQmeR1+2Na+P5dMAmanOG4dcHfqJmflhJGPhk271iMcL4loE0q87LqOYNb1C2gQiogTbY6F547gZrV8IHWNIML3B1NmxmpfaKXMDRM=
    on:
      tags: true
      repo: mediagoom/node-play
      node: 8
